<?php
class Berthe_StoreMemcached extends Berthe_AbstractStore {
    /**
     * The memcached accessor shared across all stores
     * @var Berthe_Memcached
     */
    protected static $_memcached = null;
    /**
     * @var boolean
     */
    protected $isPersistent = false;
    /**
     * @var boolean
     */
    protected $isTTLAble = true;
    /**
     * Used to force key name, otherwise generated by the memcachedname and site
     * @var string 
     */
    protected $cacheKey = null;
    /**
     * @var string
     */
    protected $memcachedName = null;
    /**
     * @var Berthe_Modules_Site_VO
     */
    protected $site = null;
    
    /**
     * @return Berthe_Memcached
     */
    public function getCacheEngine() {
        return self::$_memcached;
    }
    
    public function __construct(Berthe_Modules_Site_VO $site = null, $cacheKey = null, $memcachedName = null) {
        if (self::$_memcached === null) {
            self::$_memcached = new Berthe_Memcached();
        }
        
        $this->site = $site;
        $this->cacheKey = $cacheKey;
        $this->memcachedName = $memcachedName;
    }
    
    /**
     * Returns the base key for memcached
     */
    protected function _getBaseMemcachedKey() {
        if (is_null($this->cacheKey)) {
            $this->cacheKey = 'ev:' . $this->memcachedName . ':' . $this->appendSite() . ':';
        }
        return $this->cacheKey;
    }
    
    /**
     * Appends the suffix to the base memcahced key
     * @return string
     */
    public function getMemcachedKey($suffix) {
        return $this->_getBaseMemcachedKey() . $suffix;
    }
    
    /**
     * Appends the site name to the memcached key
     * @return string
     */
    protected function appendSite() {
        return (!is_null($this->site)) ? $this->site->computer_name : "pu"; 
    }
    
    /**
     * @param array $ids
     * @return array id=>object
     */
    protected function _load(array $ids = array()) {
        $_idsCopy = array_flip($ids);

        // Array transformation :  array[id] = id  INTO  array[memcachedId] = id
        array_walk($_idsCopy, function(&$value, $key, $context) {
            $value = $context->getMemcachedKey($key); // "ev:mc:obj:" . $value;
        }, $this);
        $_memcachedFormattedIds = array_flip($_idsCopy);
        
        // unserialized & store locally
        $_objectsFromCache = self::$_memcached->getMulti(array_keys($_memcachedFormattedIds));
        $_objects = array();
        foreach($_objectsFromCache as $_memcachedKey => &$_objectFromCache) {
            if($_objectFromCache->version == $_objectFromCache::VERSION) {
                $_objects[$_memcachedFormattedIds[$_memcachedKey]] = $_objectFromCache;
            }
        }
        return $_objects;
    }
    
    /**
     * @param array $vos
     * @return boolean
     */
    protected function _saveMulti(array $vos = array()) {
        $toSave = array();
        foreach($vos as $vo) {
            $toSave[$this->getMemcachedKey($vo->id)] = $vo;
        }
        return self::$_memcached->setMulti($toSave);
    }

    protected function _insert(Berthe_AbstractVO &$vo) {
        return self::$_memcached->set($this->getMemcachedKey($vo->id), $vo);
    }

    protected function _update(Berthe_AbstractVO &$vo) {
        return $this->_insert($vo);
    }

    protected function _delete(Berthe_AbstractVO &$vo) {
        return self::$_memcached->delete($this->getMemcachedKey($vo->id));
    }
}